/**
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to the user guide at
 * https://docs.gradle.org/current/userguide/multi_project_builds.html
 */

rootProject.name = 'FibBot'

include(':app')